# https://discord.com/developers/
DISCORD_KEY = "s3cr3t.k3y"

# Browser > F12 > Storage / Application > Cookies
HV_COOKIES = { ipb_member_id = 3950841, ipb_pass_hash = 'blarg' }

# Browser > F12 > Storage / Application > Cookies
EH_COOKIES = { ipb_member_id = 3950841 }